### ISSUE TITLE
Snackbar appears behind dialogs

### ISSUE THREAD

**Issue by hzsweers** [nispok/snackbar#76]
If I show a snackbar in response to a button clicked in a dialog, it shows behind the dialog's dim layer. It should appear on top of everything when summoned IMO

**Comment by wmora** [comment]
yeah, this is related to #27. It's because of how a dialog attaches to an Activity; I still haven't worked on this

**Comment by y2kshane** [comment]
+1 this lib would be perfect if you can fix this issue .....anyway thanks for the awsm lib

**Comment by h6ah4i** [comment]
Hi. It would be very nice if this issue fixed, but I think it's impossible to solve the issue in straightforward way. Because the Dialogs are placed on different window from Activity's one...

I forked the Snackbar library and solved this issue in a bit different way. I've added the `SnackbarManager.show(Snackbar, ViewGroup)` method and it makes user can control where to show the Snackbar. 

https://github.com/h6ah4i/snackbar/tree/feature/attach_to_non_activity_root_view

![show_in_dialog](https://cloud.githubusercontent.com/assets/2552365/6143484/e0eea676-b20c-11e4-90ad-41ab056f802d.gif)

P.S. @wmora Should I pull request the forked branch to your repository? The use of Snackbar with Dialog is not mentioned in Google's guide line though.

**Comment by wmora** [comment]
@h6ah4i I think this is the best that can be done for this particular situation. Also, your solution solves #62 too. It would be great if you create a PR for this.

**Comment by wmora** [comment]
fixed, or at least a workaround is provided, in [2.9.0](https://github.com/nispok/snackbar/releases/tag/v2.9.0)

**Comment by sharon-joshi** [comment]
This is the solution. 
just add your Dialogues view as the second parameter in Snackbar.make(context,view,CharSequence,duration)

Snackbar snackbar = Snackbar
                .make(activity,mView, message, Snackbar.LENGTH_INDEFINITE)
                .setAction("Ok", new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                    }
                });
     snackbar.show();
